### ISSUE TITLE
Onrobot 3FG15 gripper ROS control package

### ISSUE THREAD

**Issue by pala5** [Osaka-University-Harada-Laboratory/onrobot#10] opened 2023-06-01 16:59 UTC
Hi,
I've seen that you've implemented the necessary packages to control through ROS the Onrobot RG and VG grippers, but not for the 3FG ones. Are you considering doing it? 
I'm currently working with a UR10e cobot with the Onrobot 3FG15 gripper coupled, so it will be too helpful to having it.
Thanks.

**Comment by takuya-ki** [comment] 2023-06-01 22:49
@pala5 
Thank you for your question.
It is possible to create the ROS package for the 3FG15 gripper because I found the information of MODBUS registers.
But unfortunately I do not have the 3FG15 gripper.

**Comment by pala5** [comment] 2023-06-02 06:21
@takuya-ki 
Thank you for your quick response.
If you don't mind, if you could implement the ROS package, I could test it and give you feedback about its behavior.

**Comment by takuya-ki** [comment] 2023-06-02 06:27
@pala5 
Then, I will try it. Please tell me the hardware configuration you have prepared.
If you do not have a compute box and quick toolchanger, the programs of this repository will not work.
https://github.com/Osaka-University-Harada-Laboratory/onrobot#usage

**Comment by pala5** [comment] 2023-06-02 08:44
@takuya-ki 
The hardware configuration that I have is the quick tool changer coupled directly to the UR1Oe tool connector.
In the past, I have worked with a Robotiq gripper coupled directly to the UR10e robot, controlling it with the MODBUS RTU communication without using the URCAPS, so I suppose that your solutions can be extrapolated too, as you have implemented that package inspired by https://github.com/ros-industrial/robotiq.

**Comment by takuya-ki** [comment] 2023-06-08 14:10
@pala5 
It might be possible but I am not sure the solution assuming that hardware configuration.
Because the issue is not related to this repository, sorry but I will close this issue.

**Closed by takuya-ki** 2023-06-08 14:10 UTC
